spring:
  data:
    mongodb:
      uri: mongodb+srv://akashadak019:qwWPJMMCWKXckxCc@cluster0.l5iqmkg.mongodb.net/dynamic_db?retryWrites=true&w=majority&appName=Cluster0

      database: codequestdb
    redis:
      host: redis-19166.c276.us-east-1-2.ec2.redns.redis-cloud.com
      port: 19166
      username: default
      password: 5tB8hj58dSpJSkZo92ehRsW1K90xUhbL
      timeout: 60000


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: codequest.coding@gmail.com
    password: mwkrhfpipbcraiki
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8080

judge0:
  api:
    base-url: https://judge0-ce.p.rapidapi.com
    key: b8b5834c78mshcae26a3d5fc1161p103cc7jsn326ed2638a48
    host: judge0-ce.p.rapidapi.com

app:
  frontend:
    redirect-uri: http://localhost:5173

cors:
  allowed-origins: http://localhost:5173
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true


jwt:
  secret: IooOhqlz++kDnyhBOXazulK1SlfzUE1M23TnbO0d+sk=
  expiration: ${JWT_EXPIRATION:86400000}